### ISSUE TITLE
Module packaging

### ISSUE THREAD

**Issue by johnomotani** [boutproject/hypnotoad2#3]
Would be nice if hypnotoad2 was structured better and pip-installable. Todo:
- [ ] Move all the `*.py` files under a `hypnotoad2` subdirectory ~~(except the ones that should be executable?)~~
- [ ] Create a `setup.py` (including an `entry_point` for anything that should be executable)
- [ ] Upload on PyPi

@ZedThree @bendudson please feel free to expand the list above with anything I've missed!

**Comment by ZedThree** [comment]
Move everything under `hypnotoad2`, but provide an `entry_point` in `setup.py`. This will make `pip` install an executable in the appropriate place.

**Comment by johnomotani** [comment]
Github Actions have a recipe for uploading automatically to PyPi every time we make a 'release'. That sounds like a nice way to go to me. I might release a version 0.1.0 after #8 goes in and try it out. Sound good @ZedThree @bendudson?
